# Generated by Django 4.0.4 on 2022-04-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='data',
            new_name='data_all',
        ),
    ]
